increment:
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    increment:
      example: 1
      default: 1

set_counter:
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    counter_state:
      example: 1
      default: 1

complete:
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    reset_from_today:
      example: true
      default: true
      selector:
        boolean: