increment:
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    increment:
      required: false
      default: 1
      selector:
        number:
          step: 1
          mode: box

set_counter:
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    counter_state:
      required: false
      default: 1
      selector:
        number:
          step: 1
          mode: box

complete:
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    reset_from_today:
      required: false
      example: true
      default: true
      selector:
        boolean: {}
