increment:
  description: Increment counter in a chore
  target:
    entity:
      integration: chore
      domain: sensor
  fields:
    increment:
      required: true
      description: Increment to the sensor
      example: 1
      default: 1