# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml

logger:
  default: warn
  logs:
    custom_components.chore: debug

http:
  cors_allowed_origins:
    - http://localhost:8124
