name: HA Validation

on:
  workflow_call:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  "0 0 * * *"

permissions: {}

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master
