name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check