name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  ha-validation:
    name: HA Validation
    uses: ./.github/workflows/ha_validation.yaml

  validate-version:
    name: Validate version
    uses: ./.github/workflows/validate_version.yaml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - ha-validation
      - validate-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          chmod +x ./bin/*
          gh --version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        run: |
          tag=$(./bin/version.sh)
          gh release create "$tag" \
              --generate-notes \
              --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
